---
- hosts: all
  tasks:
    - name: Install deps and other needed stuff
        apt:
          pkg:
          - screen
          - lib32gcc1

    - name: add the steam user
      user:
        name: steam
        shell: /bin/bash

    - name: download steamcmd for linux
      remote_user: steam
      get_url:
        url: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        dest: ~/
        mode: 0644

    - name: extract steamcmd
      remote_user: steam
      unarchive: src=~/steamcmd_linux.tar.gz dest=~ copy=no owner=steam mode=0755

    - name: install / update warfork
      remote_user: steam
      shell: ~/steamcmd.sh +force_install_dir /warfork/ +login anonymous +app_update 1136510 +quit

    - name: copy the configs over
      remote_user: steam
      copy: src={{item}} dest=~/warfork/Warfork.app/Contents/Resources/basewf owner=steam group=steam mode=0644
      with_fileglob:
      - configs/*

    - name: copy the aliases.txt over
      remote_user: steam
      copy: src=aliases.txt dest=~ owner=steam group=steam mode=0644

    - name: append aliases.txt to .bashrc
      remote_user: steam
      command: cat ~/aliases.txt >> ~/.bashrc 
